geneva/urls.py
from django.conf.urls import url
from . import views

app_name = 'geneva'
urlpatterns = [
    # Geneva Home
    url(r'^$', views.IndexView.as_view(), name='index'),
    # Url by record ID geneva/1
    url(r'^(?P<pk>[0-9]+)/$', views.RecordView.as_view(), name='geneva_record'),
    # /geneva_record/add
    url(r'geneva_record/add/$', views.RecordCreate.as_view(), name='record-add'),
    # /geneva_record/1
    url(r'geneva_record/(?P<pk>[0-9]+)/$', views.RecordUpdate.as_view(), name='record-update'),
    # /geneva_record/1/delete
    url(r'geneva_record/(?P<pk>[0-9]+)/delete$', views.RecordDelete.as_view(), name='record-delete'),
]

rangeland/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('geneva.urls', namespace='geneva')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geneva/models.py
from django.db import models
from django.core.urlresolvers import reverse


class GvData(models.Model):
    gv_01_open_stock = models.FloatField(default=0)
    gv_02_open_stock = models.FloatField(default=0)
    gv_03_open_stock = models.FloatField(default=0)
    gv_01_close_stock = models.FloatField(default=0)
    gv_02_close_stock = models.FloatField(default=0)
    gv_03_close_stock = models.FloatField(default=0)
    gv_01_open_gauge = models.CharField(max_length=20, default="0' 0\" /16ths")
    gv_02_open_gauge = models.CharField(max_length=20, default="0' 0\" /16ths")
    gv_03_open_gauge = models.CharField(max_length=20, default="0' 0\" /16ths")
    gv_01_close_gauge = models.CharField(max_length=20, default="0' 0\" /16ths")
    gv_02_close_gauge = models.CharField(max_length=20, default="0' 0\" /16ths")
    gv_03_close_gauge = models.CharField(max_length=20, default="0' 0\" /16ths")
    gv_01_stock_change = models.FloatField(default=0)
    gv_02_stock_change = models.FloatField(default=0)
    gv_03_stock_change = models.FloatField(default=0)
    tact1_open = models.FloatField(default=0)
    tact2_open = models.FloatField(default=0)
    tact3_open = models.FloatField(default=0)
    tact4_open = models.FloatField(default=0)
    tact5_open = models.FloatField(default=0)
    tact1_close = models.FloatField(default=0)
    tact2_close = models.FloatField(default=0)
    tact3_close = models.FloatField(default=0)
    tact4_close = models.FloatField(default=0)
    tact5_close = models.FloatField(default=0)
    tact1_total = models.FloatField(default=0)
    tact2_total = models.FloatField(default=0)
    tact3_total = models.FloatField(default=0)
    tact4_total = models.FloatField(default=0)
    tact5_total = models.FloatField(default=0)
    incoming_meter_1_open = models.FloatField(default=0)
    incoming_meter_2_open = models.FloatField(default=0)
    incoming_meter_1_close = models.FloatField(default=0)
    incoming_meter_2_close = models.FloatField(default=0)
    outgoing_meter_1_open = models.FloatField(default=0)
    outgoing_meter_2_open = models.FloatField(default=0)
    outgoing_meter_1_close = models.FloatField(default=0)
    outgoing_meter_2_close = models.FloatField(default=0)
    incoming_meter_1_total = models.FloatField(default=0)
    incoming_meter_2_total = models.FloatField(default=0)
    outgoing_meter_1_total = models.FloatField(default=0)
    outgoing_meter_2_total = models.FloatField(default=0)
    incoming_meter_daily_total = models.FloatField(default=0)
    outgoing_meter_daily_total = models.FloatField(default=0)
    gsv_total = models.FloatField(default=0)
    transactions_total = models.FloatField(default=0)
    comments = models.CharField(max_length=200, default='comments')
    slug = models.SlugField(unique=True)
    report_file = models.FileField(default=None)
    pub_date = models.DateField(db_index=True)

    def __str__(self):
        return 'Geneva {} {}'.format(self.id, self.pub_date)

    def get_absolute_url(self):
        return reverse('geneva:geneva', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'GV info'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

geneva/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import GvData


class GenevaForm(forms.ModelForm):
    class Meta:
        model = GvData
        fields = ['gv_01_close_gauge', 'gv_01_close_stock', 'gv_01_stock_change',
                  'gv_02_close_gauge', 'gv_02_close_stock', 'gv_02_stock_change',
                  'gv_03_close_gauge', 'gv_03_close_stock', 'gv_03_stock_change',
                  'tact1_close', 'tact1_total', 'tact2_close', 'tact2_total',
                  'tact3_close', 'tact3_total', 'tact4_close', 'tact4_total',
                  'tact5_close', 'tact5_total', 'incoming_meter_1_close',
                  'incoming_meter_1_total', 'incoming_meter_2_close',
                  'incoming_meter_2_total', 'incoming_meter_daily_total',
                  'outgoing_meter_1_close', 'outgoing_meter_1_total',
                  'outgoing_meter_2_close', 'outgoing_meter_2_total',
                  'outgoing_meter_daily_total', 'transactions_total', 'gsv_total',
                  'comments', 'pub_date']

geneva/views.py
from django.views import generic
from .models import GvData
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect


class IndexView(generic.ListView):
    template_name = 'geneva/index.html'

    def get_queryset(self):
        return GvData.objects.all()


class RecordView(generic.DetailView):
    model = GvData
    template_name = 'geneva/geneva_record.html'


class RecordCreate(CreateView):
    model = GvData
    fields = ['gv_01_close_gauge', 'gv_01_close_stock', 'gv_01_stock_change',
              'gv_02_close_gauge', 'gv_02_close_stock', 'gv_02_stock_change',
              'gv_03_close_gauge', 'gv_03_close_stock', 'gv_03_stock_change',
              'tact1_close', 'tact1_total', 'tact2_close', 'tact2_total',
              'tact3_close', 'tact3_total', 'tact4_close', 'tact4_total',
              'tact5_close', 'tact5_total', 'incoming_meter_1_close',
              'incoming_meter_1_total', 'incoming_meter_2_close',
              'incoming_meter_2_total', 'incoming_meter_daily_total',
              'outgoing_meter_1_close', 'outgoing_meter_1_total',
              'outgoing_meter_2_close', 'outgoing_meter_2_total',
              'outgoing_meter_daily_total', 'transactions_total', 'gsv_total',
              'comments', 'pub_date', 'report_file']

    def form_valid(self, form):
        form.instance.incoming_meter_daily_total = (form.instance.incoming_meter_1_total +
                                                    form.instance.incoming_meter_2_total)
        form.save()

        return HttpResponseRedirect('geneva:index')


class RecordUpdate(UpdateView):
    model = GvData
    fields = ['gv_01_close_gauge', 'gv_01_close_stock', 'gv_01_stock_change',
              'gv_02_close_gauge', 'gv_02_close_stock', 'gv_02_stock_change',
              'gv_03_close_gauge', 'gv_03_close_stock', 'gv_03_stock_change',
              'tact1_close', 'tact1_total', 'tact2_close', 'tact2_total',
              'tact3_close', 'tact3_total', 'tact4_close', 'tact4_total',
              'tact5_close', 'tact5_total', 'incoming_meter_1_close',
              'incoming_meter_1_total', 'incoming_meter_2_close',
              'incoming_meter_2_total', 'incoming_meter_daily_total',
              'outgoing_meter_1_close', 'outgoing_meter_1_total',
              'outgoing_meter_2_close', 'outgoing_meter_2_total',
              'outgoing_meter_daily_total', 'transactions_total', 'gsv_total',
              'comments', 'pub_date', 'report_file']


class RecordDelete(DeleteView):
    model = GvData
    success_url = reverse_lazy('geneva:index')

# def meter_variables(request):
#
#     incoming_meter_daily_total = (object.incoming_meter_1_close - object.incoming_meter_1_open)
#     + (object.incoming_meter_2_close - object.incoming_meter_2_close)
#
#     return (request, 'geneva/geneva_record.html',
#                   {'incoming_meter_daily_total': incoming_meter_daily_total})

geneva/templates/geneva/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}RangeLand{% endblock %}</title>


      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'geneva/style.css'%}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">



    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

    <nav class="navbar navbar-default">
  	<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rangeland</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'geneva:index' %}">Geneva <span class="sr-only">(current)</span></a></li>
        <li><a href="#">State Line</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'geneva:record-add' %}">Add Record</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="Date" class="form-control" placeholder="Date">
          <button type="submit" class="btn btn-defualt">Submit</button>
        </div>

      </form>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<body>
{% block content %}
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

geneva/templates/geneva/form-template.html
{% for field in form %}
    <div class="form-group">
        <div>
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
    <label>{{ field.label_tag }}</label>
    <div>{{ field }}</div>
    </div>

{% endfor %}

geneva/templates/geneva/geneva_record.html
{% extends 'geneva/base.html' %}
{% load mathfilters %}
{% block title %}{{ object.id }}    {{ object.pub_date }}{% endblock %}


{% block content %}
    <h1>record view</h1>
    <h1>{{ object.pub_date }}</h1>
    <h3>{{ object.id }}</h3>
    <div class="container-fluid">
		<table class ="table table-bordered tank-table">
			<div class="col-xs-6 col-md-4">
				<tr>
					<th>Tank</th>
					<th>Opening Gauge</th>
					<th>BBLS Open Stock</th>
					<th>Closing Gauge</th>
					<th>BBLS Closing Stock</th>
					<th>Stock Change</th>
				<tr>


				<tr>
					<th>GV-01</th>
					<td><input type="text" class="form-control" placeholder="Open Gauge" value="{{ object.gv_01_open_gauge }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="BBLS Open Stock" value="{{ object.gv_01_open_stock }}"/></td>
			     	<td><input type="text" class="form-control" placeholder="Closing Gauge" value="{{ object.gv_01_close_gauge }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="BBLS Closing Stock" value="{{ object.gv_01_close_stock }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="Stock Change"
                               value="{{ object.gv_01_close_stock|sub:object.gv_01_open_stock }}"/></td>
				</tr>



				<tr>
					<th>GV-02</th>
					<td><input type="text" class="form-control" placeholder="Open Gauge" value="{{ object.gv_02_open_gauge }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="BBLS Open Stock" value="{{ object.gv_02_open_stock }}"/></td>
			     	<td><input type="text" class="form-control" placeholder="Closing Gauge" value="{{ object.gv_02_close_gauge }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="BBLS Closing Stock" value="{{ object.gv_02_close_stock }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="Stock Change"
                               value="{{ object.gv_02_close_stock|sub:object.gv_02_open_stock }}"/></td>
				</tr>



				<tr>
					<th>GV-03</th>
					<td><input type="text" class="form-control" placeholder="Open Gauge" value="{{ object.gv_03_open_gauge }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="BBLS Open Stock" value="{{ object.gv_03_open_stock }}"/></td>
			     	<td><input type="text" class="form-control" placeholder="Closing Gauge" value="{{ object.gv_03_close_gauge }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="BBLS Closing Stock" value="{{ object.gv_03_close_stock }}"/></td>
			      	<td><input type="number" class="form-control" placeholder="Stock Change"
                               value="{{ object.gv_03_close_stock|sub:object.gv_03_open_stock }}"/></td>
				</tr>
			</div>
		</table>
	</div>

	<div class="container-fluid">
		<table class="table table-bordered tact-table">
			<div class="col-xs-6 col-md-4">

				<tr>
					<th>Tact #</th>
					<th>Start</th>
					<th>End</th>
					<th>Totals</th>

				</tr>

				<tr>
					<th>Tact #1</th>
					<td><input type="number" class="form-control" placeholder="Open" value="{{ object.tact1_open }}"/></td>
					<td><input type="number" class="form-control" placeholder="Close" value="{{ object.tact1_close }}"/></td>
					<td><input type="number" class="form-control" placeholder="Total"
                               value="{{ object.tact1_close|sub:object.tact1_open }}"/></td>

				<tr>
					<th>Tact #2</th>
					<td><input type="number" class="form-control" placeholder="Open" value="{{ object.tact2_open }}"/></td>
					<td><input type="number" class="form-control" placeholder="Close" value="{{ object.tact2_close }}"/></td>
					<td><input type="number" class="form-control" placeholder="Total"
                               value="{{ object.tact2_close|sub:object.tact2_open }}"/></td>

				<tr>
					<th>Tact #3</th>
					<td><input type="number" class="form-control" placeholder="Open" value="{{ object.tact3_open }}"/></td>
					<td><input type="number" class="form-control" placeholder="Close" value="{{ object.tact3_close }}"/></td>
					<td><input type="number" class="form-control" placeholder="Total"
                               value="{{ object.tact3_close|sub:object.tact3_open }}"/></td>

				</tr>
				<tr>
					<th>Tact #4</th>
					<td><input type="number" class="form-control" placeholder="Open" value="{{ object.tact4_open }}"/></td>
					<td><input type="number" class="form-control" placeholder="Close" value="{{ object.tact4_close }}"/></td>
					<td><input type="number" class="form-control" placeholder="Total"
                               value="{{ object.tact4_close|sub:object.tact4_open }}"/></td>
				</tr>
				<tr>
					<th>Tact #5</th>
					<td><input type="number" class="form-control" placeholder="Open" value="{{ object.tact5_open }}"/></td>
					<td><input type="number" class="form-control" placeholder="Close" value="{{ object.tact5_close }}"/></td>
					<td><input type="number" class="form-control" placeholder="Total"
                               value="{{ object.tact5_close|sub:object.tact5_open }}"/></td>

				<tr>
					<th># of Transactions</th>
					<td><input type="number" class="form-control" value="{{ object.transactions_total }}"/></td>
				</tr>
				<tr>
					<th>GSV Total</th>
					<td><input type="number" class="form-control" value="{{ object.gsv_total }}"/></td>
				</tr>




			</div>
		</table>
	</div>

	<div class="container-fluid">
		<table class="table table-bordered omni-table">

			<div class="col-xs-6 col-md-4 text-center">

					<tr>
						<th class="meter1-head">From Stateline</th>

					</tr>
					<tr>
						<th>Meter</th>
						<th>Open</th>
						<th>Close</th>
						<th>GV-01</th>
						<th>GV-02</th>
						<th>GV-03</th>
						<th>Daily Total</th>
					</tr>
					<tr>
						<th>Meter #1 (EAST)</th>
						<td><input type="number" class="form-control" placeholder="Meter 1 Open"
                                   value="{{ object.incoming_meter_1_open }}"/></td>
						<td><input type="number" class="form-control" placeholder="Meter 1 Close"
                                   value="{{ object.incoming_meter_1_close }}"/></td>
						<div class="btn-group" data-toggle="buttons" id="radioopt">
							  <td><label class="btn btn-primary active">
							    <input type="radio" name="options" id="option1">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option2">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option3">
							  </label>
							  </td>
						</div>

						<td><input type="number" class="form-control" placeholder="Daily Total"
                                   value="{{ object.incoming_meter_1_total }}"/>
                        </td>

					</tr>
					<tr>
						<th>Meter #2 (WEST)</th>
						<td><input type="number" class="form-control" placeholder="Meter 2 Open"
                                   value="{{ object.incoming_meter_2_open }}"/></td>
						<td><input type="number" class="form-control" placeholder="Meter 2 Close"
                                   value="{{ object.incoming_meter_2_close }}"/></td>
						<div class="btn-group" data-toggle="buttons" id="radioopt">
							  <td><label class="btn btn-primary active">
							    <input type="radio" name="options" id="option1">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option2">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option3">
							  </label>
							  </td>
						</div>
						<td><input type="number" class="form-control" placeholder="Daily Total"
                                   value="{{ object.incoming_meter_2_total }}"/>
                        </td>
                    <tr>




						<th>Total</th>
						<td><input type="number" class="form-control" placeholder="Combined Total"
                                   value="{{ object.incoming_meter_daily_total }}"/></td>

					</tr>

			</div>
		</table>
	</div>

	<div class="container-fluid">
		<table class="table table-bordered omni-table">

			<div class="col-xs-6 col-md-4 text-center">

					<tr>
						<th class="meter2-head">Outbound to Plains</th>

					</tr>
					<tr>
						<th>Meter</th>
						<th>Open</th>
						<th>Close</th>
						<th>GV-01</th>
						<th>GV-02</th>
						<th>GV-03</th>
						<th>Daily Total</th>
					</tr>
					<tr>
						<th>Meter #1 (EAST)</th>
						<td><input type="number" class="form-control" placeholder="Meter 1 Open"
                                   value="{{ object.outgoing_meter_1_open }}"/></td>
						<td><input type="number" class="form-control" placeholder="Meter 1 Close"
                                   value="{{ object.outgoing_meter_1_close }}"/></td>
						<div class="btn-group" data-toggle="buttons" id="radioopt">
							  <td><label class="btn btn-primary active">
							    <input type="radio" name="options" id="option1">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option2">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option3">
							  </label>
							  </td>
						</div>
						<td><input type="number" class="form-control" placeholder="Daily Total"
                                   value="{{ object.outgoing_meter_1_close|sub:object.outgoing_meter_1_open }}"/>
                        </td>

					</tr>
					<tr>
						<th>Meter #2 (WEST)</th>
						<td><input type="number" class="form-control" placeholder="Meter 2 Open"
                                   value="{{ object.outgoing_meter_2_open }}"/></td>
						<td><input type="number" class="form-control" placeholder="Meter 2 Close"
                                   value="{{ object.outgoing_meter_2_close }}"/></td>
						<div class="btn-group" data-toggle="buttons" id="radioopt">
							  <td><label class="btn btn-primary active">
							    <input type="radio" name="options" id="option1">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option2">
							  </label>
							  </td>
							  <td>
							  <label class="btn btn-primary">
							    <input type="radio" name="options" id="option3">
							  </label>
							  </td>
						</div>
						<td><input type="number" class="form-control" placeholder="Daily Total"
                                   value="{{ object.outgoing_meter_2_close|sub:object.outgoing_meter_2_open }}"/>
                        </td>



					</tr>
					<tr>


						<th>Total</th>
						<td><input type="number" class="form-control" placeholder="Combined Total"
                                   value=""/></td>

					</tr>
			</div>
		</table>
	</div>

	<div class="container-fluid">

		<div class="form-group">
  		<label for="comment">Comments:</label>
  		<textarea class="form-control" rows="5" id="comments" value="{{ object.comments }}"></textarea>
		</div>

	</div>


{% endblock %}

geneva/templates/geneva/gvdata_form.html
{% extends 'geneva/base.html' %}
{% block title %}Create Geneva Record{% endblock %}
{% block active_record %}Active {% endblock %}

{% block content %}

    <h1>Create Geneva Record</h1>
    <form class="" action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {% include 'geneva/form-template.html' %}


    <div class="form-group">
        <div class="col-xs-6 col-md-4">
            <button type="submit" class="btn-danger">Submit</button>
        </div>
    </div>

    </form>

{% endblock %}

geneva/templates/geneva/index.html
{% extends 'geneva/base.html'%}
{% block title %}Geneva Records{% endblock %}

{% block content %}
  <h1>Home Page</h1>


    <h1>Geneva Report Records</h1>
    <ul>
        {% for record in object_list %}
        <li><a href="{% url 'geneva:geneva_record' record.id %}">{{ record.pub_date }}</a>

            <form action="{% url 'geneva:record-update' record.id %}" method="get" style="display: inline">

                {% csrf_token %}
                <button class="btn btn-success" >Update Record</button>

            </form><form action="{% url 'geneva:record-delete' record.id %}" method="post" style="display: inline">

                {% csrf_token %}
                <button class="btn btn-danger" >Delete Record</button>

            </form>
        </li>
        {% endfor %}
    </ul>


{% endblock %}